managed-keys-zone: loaded serial 0
zone 0.in-addr.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:2f::f#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:7fd::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:f::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:e::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:b::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:c::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:48::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:40::1#53
network unreachable resolving 'centos.org/DS/IN': 2001:500:40::1#53
network unreachable resolving 'mirror.epn.edu.ec/A/IN': 2801:14:a000::10#53
network unreachable resolving 'mirror.espoch.edu.ec/A/IN': 2800:68:a:7101::3#53
network unreachable resolving 'mirror.ci.ifes.edu.br/A/IN': 2001:12f0:6e1:1::2#53
network unreachable resolving 'mirror.ci.ifes.edu.br/A/IN': 2001:12f0:6e1:1::3#53
network unreachable resolving 'mirror.ufam.edu.br/A/IN': 2001:12f0:d1c::3#53
network unreachable resolving 'mirror.ufam.edu.br/A/IN': 2001:12f0:d1c::2#53
network unreachable resolving 'centos.ufes.br/A/IN': 2001:12f0:6d0:f050::10#53
network unreachable resolving 'centos.ufes.br/A/IN': 2001:12f0:6d0:f050::11#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:503:d414::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:503:39c1::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:501:b1f9::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:502:7094::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:503:83eb::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:502:8cc::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:503:d2d::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:500:856e::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:502:1ca1::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:503:eea3::30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:503:231d::2:30#53
network unreachable resolving 'ns2.he.net/AAAA/IN': 2001:500:d937::30#53
network unreachable resolving 'ns4.he.net/AAAA/IN': 2001:502:8cc::30#53
network unreachable resolving 'com.br/DS/IN': 2001:12f8:4::10#53
network unreachable resolving 'com.br/DS/IN': 2001:12f8:a::10#53
network unreachable resolving 'com.br/DS/IN': 2001:12f8:c::10#53
network unreachable resolving 'com.br/DS/IN': 2001:12f8:8::10#53
network unreachable resolving 'com.br/DS/IN': 2001:12f8:2::10#53
network unreachable resolving 'edu.br/DS/IN': 2001:12f8:8::10#53
network unreachable resolving 'mirror.unimagdalena.edu.co/A/IN': 2610:a1:1011::21#53
network unreachable resolving 'mirror.unimagdalena.edu.co/A/IN': 2610:a1:1010::21#53
network unreachable resolving 'mirror.unimagdalena.edu.co/A/IN': 2001:502:2eda::21#53
network unreachable resolving 'mirror.unimagdalena.edu.co/A/IN': 2610:a1:1012::21#53
network unreachable resolving 'mirror.unimagdalena.edu.co/A/IN': 2001:502:ad09::21#53
network unreachable resolving 'mirror.unimagdalena.edu.co/A/IN': 2610:a1:1009::21#53
network unreachable resolving 'ns4.he.net/AAAA/IN': 2001:470:500::2#53
network unreachable resolving 'ns4.he.net/AAAA/IN': 2001:470:100::2#53
network unreachable resolving 'ns4.he.net/AAAA/IN': 2001:470:300::2#53
network unreachable resolving 'ns4.he.net/AAAA/IN': 2001:470:200::2#53
network unreachable resolving 'ns4.he.net/AAAA/IN': 2001:470:400::2#53
network unreachable resolving 'edu.co/DS/IN': 2610:a1:1010::21#53
network unreachable resolving 'mirror.globo.com/A/IN': 2804:294:8000:200:177:53:95:213#53
network unreachable resolving 'mirror.globo.com/A/IN': 2804:294:100:803:131:0:24:26#53
network unreachable resolving 'mirror.globo.com/A/IN': 2804:294:4000:8001::5#53
network unreachable resolving 'centos.pop-es.rnp.br/A/IN': 2400:cb00:2049:1::a29f:bba#53
network unreachable resolving 'centos.pop-es.rnp.br/A/IN': 2400:cb00:2049:1::a29f:9cc#53
network unreachable resolving 'centos.pop-es.rnp.br/A/IN': 2400:cb00:2049:1::a29f:857#53
network unreachable resolving 'centos.pop-es.rnp.br/A/IN': 2400:cb00:2049:1::a29f:a80#53
network unreachable resolving 'centos.pop-es.rnp.br/A/IN': 2001:12f0:6c0:5128::131#53
network unreachable resolving 'centos.pop-es.rnp.br/A/IN': 2001:12f0:6c0:5128::132#53
network unreachable resolving 'ftp.unicamp.br/A/IN': 2001:12f8:a::10#53
network unreachable resolving 'ftp.unicamp.br/A/IN': 2801:8a:2003::2#53
network unreachable resolving 'ftp.unicamp.br/A/IN': 2801:8a:4003::3#53
network unreachable resolving 'ftp.unicamp.br/A/IN': 2001:12d8:88:30::2#53
network unreachable resolving 'mirror.ufscar.br/A/IN': 2801:b0:d0:2100::232#53
network unreachable resolving 'mirror.ufscar.br/A/IN': 2801:b0:100::4#53
network unreachable resolving 'mirror.ufscar.br/A/IN': 2801:b0:b0::29#53
network unreachable resolving 'mirror.ufscar.br/A/IN': 2801:b0:200::4#53
network unreachable resolving 'mirror.ufscar.br/A/IN': 2801:b0:c0:2102::235#53
network unreachable resolving 'dawn.ns.cloudflare.com/A/IN': 2400:cb00:2049:1::a29f:7e2#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2400:cb00:2049:1::a29f:21#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2400:cb00:2049:1::a29f:21#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2803:f800:50::6ca2:c06a#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2606:4700:50::adf5:3a6a#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2a06:98c1:50::ac40:206a#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2a06:98c1:50::ac40:21b0#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2606:4700:58::adf5:3bb0#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2803:f800:50::6ca2:c1b0#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br.www.tendawifi.com/A/IN': 2400:3200:2000:36::1#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br.www.tendawifi.com/A/IN': 2400:3200:2000:37::1#53
network unreachable resolving 'fe1.galeb.globo.com/A/IN': 2804:294:100:803:131:0:24:26#53
network unreachable resolving 'fe1.galeb.globo.com/A/IN': 2804:294:4000:8001::5#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
network unreachable resolving 'mirror.pop-es.rnp.br/A/IN': 2001:12f0:6c0:5128::131#53
network unreachable resolving 'mirror.pop-es.rnp.br/A/IN': 2001:12f0:6c0:5128::132#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
network unreachable resolving 'ufscar.br/DNSKEY/IN': 2801:b0:c0:2102::235#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'ufscar.br/DS/IN': 2001:12f8:8::10#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2803:f800:50::6ca2:c1b0#53
network unreachable resolving 'ufscar.br/DS/IN': 2001:12f8:a::10#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'mirror.turbozoneinternet.net.br/A/IN': 2804:203c::12#53
network unreachable resolving 'mirror.turbozoneinternet.net.br/A/IN': 2804:203c::9#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
network unreachable resolving 'net.br/DS/IN': 2001:12f8:8::10#53
network unreachable resolving 'net.br/DS/IN': 2001:12f8:a::10#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
network unreachable resolving 'turbozoneinternet.net.br/DS/IN': 2001:12f8:a::10#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
no valid DS resolving 'mirror-centos-jpa.hostdime.com.br.www.tendawifi.com/A/IN': 106.11.211.57#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
no valid DS resolving 'mirror-centos-jpa.hostdime.com.br.www.tendawifi.com/A/IN': 140.205.41.28#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
no valid DS resolving 'mirror-centos-jpa.hostdime.com.br.www.tendawifi.com/A/IN': 140.205.41.17#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
no valid DS resolving 'mirror-centos-jpa.hostdime.com.br.www.tendawifi.com/A/IN': 106.11.141.128#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
no valid DS resolving 'mirror-centos-jpa.hostdime.com.br.www.tendawifi.com/A/IN': 106.11.211.67#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
network unreachable resolving 'mirror.ufam.edu.br/AAAA/IN': 2001:12f0:d1c::2#53
network unreachable resolving 'mirror.ufam.edu.br/AAAA/IN': 2001:12f0:d1c::3#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/AAAA/IN': 2606:4700:58::adf5:3bb0#53
network unreachable resolving 'ftp.unicamp.br/AAAA/IN': 2801:8a:2003::2#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 2
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.168.192.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 3
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 1.168.192.in-addr.arpa/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:dc3::35#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:500:a8::e#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:502:1ca1::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:502:7094::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:502:8cc::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:500:d937::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:503:39c1::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:501:b1f9::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:503:d414::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:503:83eb::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:500:856e::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:503:231d::2:30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:503:eea3::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2001:503:d2d::30#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2400:3200:2000:37::1#53
network unreachable resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 2400:3200:2000:36::1#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
no valid DS resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 106.11.141.128#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
no valid DS resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 106.11.211.57#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
no valid DS resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 140.205.81.28#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
no valid DS resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 106.11.211.67#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
no valid DS resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 106.11.211.68#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
no valid DS resolving 'pc1.henrycodigo.com.www.tendawifi.com/A/IN': 106.11.141.118#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 4
zone 0.in-addr.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:500:1::53#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:7fe::53#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:500:12::d0d#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:501:b1f9::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:503:83eb::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:502:1ca1::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:500:856e::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:502:7094::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:500:d937::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:503:eea3::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:503:d2d::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:503:d414::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:503:39c1::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:503:231d::2:30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2001:502:8cc::30#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2400:3200:2000:36::1#53
network unreachable resolving 'www.www.tendawifi.com/A/IN': 2400:3200:2000:37::1#53
network unreachable resolving 'com/DS/IN': 2001:7fe::53#53
network unreachable resolving 'com/DS/IN': 2001:500:1::53#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
no valid DS resolving 'www.www.tendawifi.com/A/IN': 140.205.81.27#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
no valid DS resolving 'www.www.tendawifi.com/A/IN': 106.11.211.58#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
no valid DS resolving 'www.www.tendawifi.com/A/IN': 106.11.211.57#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
no valid DS resolving 'www.www.tendawifi.com/A/IN': 106.11.141.118#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
no valid DS resolving 'www.www.tendawifi.com/A/IN': 106.11.141.127#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
no valid DS resolving 'www.www.tendawifi.com/A/IN': 140.205.81.28#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.42.93.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.35.51.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.55.83.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.12.94.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.33.14.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.26.92.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.48.79.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.54.112.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.43.172.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.31.80.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.52.178.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.41.162.30#53
FORMERR resolving 'tendawifi.com/DS/IN': 192.5.6.30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:eea3::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d414::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:1ca1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:231d::2:30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:83eb::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:7094::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:502:8cc::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:39c1::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:d2d::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:500:d937::30#53
network unreachable resolving 'tendawifi.com/DS/IN': 2001:503:a83e::2:30#53
no valid DS resolving 'www.www.tendawifi.com/A/IN': 140.205.41.17#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 5
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.168.192.in-addr.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 6
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.168.192.in-addr.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 7
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
network unreachable resolving 'web/A/IN': 2001:500:2::c#53
network unreachable resolving 'web/A/IN': 2001:500:2d::d#53
network unreachable resolving 'web/A/IN': 2001:503:ba3e::2:30#53
network unreachable resolving 'web/A/IN': 2001:500:2f::f#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:500:2d::d#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:503:83eb::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:502:7094::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:501:b1f9::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:503:eea3::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:500:d937::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:503:231d::2:30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:503:d2d::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:500:856e::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:502:1ca1::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:503:d414::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:503:39c1::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2001:502:8cc::30#53
network unreachable resolving 'www.facebook.com/A/IN': 2a03:2880:f1fc:c:face:b00c:0:35#53
network unreachable resolving 'www.facebook.com/A/IN': 2a03:2880:f0fd:c:face:b00c:0:35#53
network unreachable resolving 'www.facebook.com/A/IN': 2a03:2880:f1fd:c:face:b00c:0:35#53
network unreachable resolving 'www.facebook.com/A/IN': 2a03:2880:f0fc:c:face:b00c:0:35#53
network unreachable resolving 'facebook.com/DS/IN': 2001:500:856e::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f0fc:c:face:b00c:0:35#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f1fc:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f0fc:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f0fd:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f1fd:b:face:b00c:0:99#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 8
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 1.168.192.in-addr.arpa/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:503:ba3e::2:30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:500:12::d0d#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:500:9f::42#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:503:83eb::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:500:856e::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:502:7094::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:503:231d::2:30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:502:1ca1::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:503:eea3::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:500:d937::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:503:d414::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:501:b1f9::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:503:d2d::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:502:8cc::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2001:503:39c1::30#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f1fd:c:face:b00c:0:35#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f1fc:c:face:b00c:0:35#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f0fc:c:face:b00c:0:35#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f0fd:c:face:b00c:0:35#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f0fd:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f1fd:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f0fc:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/A/IN': 2a03:2880:f1fc:b:face:b00c:0:99#53
network unreachable resolving 'facebook.com/DS/IN': 2001:501:b1f9::30#53
network unreachable resolving 'facebook.com/DS/IN': 2001:503:a83e::2:30#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 9
zone 0.in-addr.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone 1.168.192.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:12::d0d#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:9f::42#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:2f::f#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:e::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:48::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:c::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:40::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:b::1#53
network unreachable resolving 'mirrorlist.centos.org/A/IN': 2001:500:f::1#53
network unreachable resolving 'centos.org/DS/IN': 2001:500:e::1#53
network unreachable resolving 'org/DNSKEY/IN': 2001:500:e::1#53
network unreachable resolving 'd.dns.br/A/IN': 2001:12f8:c::10#53
network unreachable resolving 'mirror.facom.ufms.br/A/IN': 2001:12f0:c41:2::8b#53
network unreachable resolving 'mirror.facom.ufms.br/A/IN': 2001:12f0:c41:2::5#53
network unreachable resolving 'yacare.pop-ms.rnp.br/AAAA/IN': 2400:cb00:2049:1::a29f:a80#53
network unreachable resolving 'yacare.pop-ms.rnp.br/AAAA/IN': 2400:cb00:2049:1::a29f:bba#53
network unreachable resolving 'yacare.pop-ms.rnp.br/AAAA/IN': 2400:cb00:2049:1::a29f:9cc#53
network unreachable resolving 'yacare.pop-ms.rnp.br/AAAA/IN': 2400:cb00:2049:1::a29f:857#53
network unreachable resolving 'yacare.pop-ms.rnp.br/A/IN': 2400:cb00:2049:1::a29f:a80#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2001:12f8:8::10#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2001:12f8:a::10#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2001:12f8:2::10#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2001:12f8:4::10#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/A/IN': 2001:12f8:c::10#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:500:856e::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:503:39c1::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:500:d937::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:503:d2d::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:500:d937::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:503:d2d::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:503:d414::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:503:d414::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:502:8cc::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:501:b1f9::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:502:8cc::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:501:b1f9::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:503:83eb::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:503:83eb::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:503:eea3::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:503:eea3::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:502:1ca1::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:503:231d::2:30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:502:1ca1::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:503:231d::2:30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:502:7094::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/AAAA/IN': 2001:500:856e::30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2001:502:7094::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/A/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'dawn.ns.cloudflare.com/A/IN': 2001:503:83eb::30#53
network unreachable resolving 'dawn.ns.cloudflare.com/A/IN': 2001:500:856e::30#53
network unreachable resolving 'henry.ns.cloudflare.com/AAAA/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'henry.ns.cloudflare.com/A/IN': 2400:cb00:2049:1::a29f:21#53
network unreachable resolving 'dawn.ns.cloudflare.com/A/IN': 2400:cb00:2049:1::a29f:7e2#53
network unreachable resolving 'com.br/DS/IN': 2001:12f8:8::10#53
network unreachable resolving 'ns4.cloudflare.com/A/IN': 2001:503:a83e::2:30#53
network unreachable resolving 'ns6.cloudflare.com/AAAA/IN': 2400:cb00:2049:1::a29f:837#53
network unreachable resolving 'ns6.cloudflare.com/AAAA/IN': 2400:cb00:2049:1::a29f:606#53
network unreachable resolving 'ns7.cloudflare.com/A/IN': 2400:cb00:2049:1::a29f:408#53
network unreachable resolving 'ns7.cloudflare.com/A/IN': 2400:cb00:2049:1::a29f:121#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/AAAA/IN': 2606:4700:58::adf5:3bb0#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/AAAA/IN': 2a06:98c1:50::ac40:206a#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/AAAA/IN': 2a06:98c1:50::ac40:21b0#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/AAAA/IN': 2803:f800:50::6ca2:c06a#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/AAAA/IN': 2803:f800:50::6ca2:c1b0#53
network unreachable resolving 'mirror-centos-jpa.hostdime.com.br/AAAA/IN': 2606:4700:50::adf5:3a6a#53
network unreachable resolving 'mirror.ufam.edu.br/A/IN': 2001:12f8:2::10#53
network unreachable resolving 'mirror.ufam.edu.br/A/IN': 2001:12f0:d1c::3#53
network unreachable resolving 'mirror.ufam.edu.br/A/IN': 2001:12f0:d1c::2#53
network unreachable resolving 'mirror.ufam.edu.br/AAAA/IN': 2001:12f0:d1c::3#53
network unreachable resolving 'facebook.com/CNAME/IN': 2a03:2880:f0fd:c:face:b00c:0:35#53
network unreachable resolving 'facebook.com/CNAME/IN': 2a03:2880:f1fd:c:face:b00c:0:35#53
network unreachable resolving 'facebook.com/CNAME/IN': 2a03:2880:f1fc:c:face:b00c:0:35#53
network unreachable resolving 'facebook.com/CNAME/IN': 2a03:2880:f0fc:c:face:b00c:0:35#53
network unreachable resolving 'star-mini.c10r.facebook.com/CNAME/IN': 2a03:2880:f0fc:c:face:b00c:0:35#53
network unreachable resolving 'star-mini.c10r.facebook.com/CNAME/IN': 2a03:2880:f0fd:c:face:b00c:0:35#53
network unreachable resolving 'star-mini.c10r.facebook.com/CNAME/IN': 2a03:2880:f0fc:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/CNAME/IN': 2a03:2880:f1fc:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/CNAME/IN': 2a03:2880:f1fd:b:face:b00c:0:99#53
network unreachable resolving 'star-mini.c10r.facebook.com/CNAME/IN': 2a03:2880:f0fd:b:face:b00c:0:99#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 10
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 11
zone 0.in-addr.arpa/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 12
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 0.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 13
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone 0.168.192.in-addr.arpa/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 14
zone 0.in-addr.arpa/IN: loaded serial 0
zone 0.168.192.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone henrycodigo.com/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone 50.168.192.in-addr.arpa/IN: loaded serial 0
zone servicios.com/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
all zones loaded
running
network unreachable resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './NS/IN': 2001:503:ba3e::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:2d::d#53
network unreachable resolving './NS/IN': 2001:500:2d::d#53
network unreachable resolving './DNSKEY/IN': 2001:500:1::53#53
network unreachable resolving './NS/IN': 2001:500:1::53#53
network unreachable resolving './DNSKEY/IN': 2001:dc3::35#53
network unreachable resolving './NS/IN': 2001:dc3::35#53
network unreachable resolving './DNSKEY/IN': 2001:500:9f::42#53
network unreachable resolving './NS/IN': 2001:500:9f::42#53
network unreachable resolving './DNSKEY/IN': 2001:500:2::c#53
network unreachable resolving './NS/IN': 2001:500:2::c#53
network unreachable resolving './DNSKEY/IN': 2001:7fe::53#53
network unreachable resolving './NS/IN': 2001:7fe::53#53
network unreachable resolving './DNSKEY/IN': 2001:503:c27::2:30#53
network unreachable resolving './NS/IN': 2001:503:c27::2:30#53
network unreachable resolving './DNSKEY/IN': 2001:500:200::b#53
network unreachable resolving './NS/IN': 2001:500:200::b#53
network unreachable resolving './DNSKEY/IN': 2001:7fd::1#53
network unreachable resolving './NS/IN': 2001:7fd::1#53
network unreachable resolving './DNSKEY/IN': 2001:500:a8::e#53
network unreachable resolving './NS/IN': 2001:500:a8::e#53
network unreachable resolving './DNSKEY/IN': 2001:500:2f::f#53
network unreachable resolving './NS/IN': 2001:500:2f::f#53
network unreachable resolving './DNSKEY/IN': 2001:500:12::d0d#53
network unreachable resolving './NS/IN': 2001:500:12::d0d#53
managed-keys-zone: Key 20326 for zone . acceptance timer complete: key now trusted
resolver priming query complete
network unreachable resolving 'servidor/A/IN': 2001:500:9f::42#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.50.3#53
no longer listening on ::1#53
exiting
